name: Tests unitaires python

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Tests à implémenter"
      